# Gopkg.toml

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.6.0"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[prune]
  go-tests = true
  unused-packages = true
